### ISSUE TITLE
bot start error

### ISSUE THREAD

**Issue by Haargrad** [BlackSamorez/ebanko#6]
when using a large model (https://huggingface.co/BlackSamorez/ebanko-large), the bot gives an error on startup

app_1            |     self.load_wsgi()
app_1            |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
app_1            |     self.wsgi = self.app.wsgi()
app_1            |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
app_1            |     self.callable = self.load()
app_1            |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
app_1            |     return self.load_wsgiapp()
app_1            |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
app_1            |     return util.import_app(self.app_uri)
app_1            |   File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
app_1            |     mod = importlib.import_module(module)
app_1            |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
app_1            |     return _bootstrap._gcd_import(name[level:], package, level)
app_1            |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
app_1            |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
app_1            |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
app_1            |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
app_1            |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
app_1            |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
app_1            |   File "/app/server.py", line 13, in <module>
app_1            |     model = Ebanko()
app_1            |   File "/app/Ebanko.py", line 11, in __init__
app_1            |     self.model = AutoModelForCausalLM.from_pretrained("model").to(DEVICE)
app_1            |   File "/usr/local/lib/python3.7/site-packages/transformers/models/auto/auto_factory.py", line 449, in from_pretrained
app_1            |     f"Unrecognized configuration class {config.__class__} for this kind of AutoModel: {cls.__name__}.\n"
app_1            | ValueError: Unrecognized configuration class <class 'transformers.models.t5.configuration_t5.T5Config'> for this kind of AutoModel: AutoModelForCausalLM.
app_1            | Model type should be one of XGLMConfig, QDQBertConfig, TrOCRConfig, GPTJConfig, PLBartConfig, RemBertConfig, RoFormerConfig, BigBirdPegasusConfig, GPTNeoConfig, BigBirdConfig, Speech2Text2Config, BlenderbotSmallConfig, BertGenerationConfig, CamembertConfig, XLMRobertaXLConfig, XLMRobertaConfig, PegasusConfig, MarianConfig, MBartConfig, MegatronBertConfig, BartConfig, BlenderbotConfig, ReformerConfig, RobertaConfig, BertConfig, OpenAIGPTConfig, GPT2Config, TransfoXLConfig, XLNetConfig, XLMProphetNetConfig, ProphetNetConfig, XLMConfig, CTRLConfig, ElectraConfig, Data2VecTextConfig.
app_1            | [2022-10-21 16:42:59 +0000] [456] [INFO] Worker exiting (pid: 456)
app_1            | [2022-10-21 16:43:00 +0000] [453] [INFO] Shutting down: Master
app_1            | [2022-10-21 16:43:00 +0000] [453] [INFO] Reason: Worker failed to boot.
app_1            | 2022-10-21 16:43:00,226 INFO exited: app (exit status 3; not expected)
app_1            | 2022-10-21 16:43:01,229 INFO spawned: 'app' with pid 466
app_1            | [2022-10-21 16:43:01 +0000] [466] [INFO] Starting gunicorn 20.1.0
app_1            | [2022-10-21 16:43:01 +0000] [466] [INFO] Listening at: http://0.0.0.0:8080 (466)
app_1            | [2022-10-21 16:43:01 +0000] [466] [INFO] Using worker: sync
app_1            | [2022-10-21 16:43:01 +0000] [469] [INFO] Booting worker with pid: 469
app_1            | 2022-10-21 16:43:02,597 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by BlackSamorez** [comment]
You should use this model.
https://huggingface.co/BlackSamorez/rudialogpt3_medium_based_on_gpt2_2ch
The other ones were for different purposes

**Comment by Haargrad** [comment]
thank you
