### ISSUE TITLE
Ability to control message frequency and length

### ISSUE THREAD

**Issue by Haargrad** [BlackSamorez/ebanko#7]
Is it possible to add a function/command that will allow you to control the frequency of generated messages? For example, a random number from 1 to 100 will be given for each message, and if the number is more than 80, the bot will answer, in other cases it will remain silent. also if possible, control the length of the message

**Comment by BlackSamorez** [comment]
It's already implemented for group messages with `/perc` bot command which accepts values from 0 to 1 to be set as probability.
The length can be controlled in [Ebanko.py](https://github.com/BlackSamorez/ebanko/blob/85d4ca82ab643ac2fa036dfd362ec43875f81137/app/app/Ebanko.py#L16) in `model.generate` call but it can't be changed in runtime now:

**Comment by Haargrad** [comment]
thank you
